version: '3'

services:
  app:
    image: infracloudio/csvserver:latest
    ports:
      - 9393:9300
    volumes:
      - /home/cloud_user/csvserver/solution/inputFile:/csvserver/inputdata:ro
    environment:
     - CSVSERVER_BORDER=Orange
